### ISSUE TITLE
ssz_generic tests without ssz field

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1079]
In `ssz_generic/unit/unit_bounds.yaml` I noticed this test:

```yaml
- type: uint16
  valid: false
  value: '-1'
  tags: [atomic, uint, uint_underflow]
```
I'm just wondering if this test should live in the SSZ tests? It seems to test an implementation of `uint16` as opposed to an SSZ implementation.

CC @protolambda
