### ISSUE TITLE
Some of the BLS fast_aggregate_verify tests are incorrect in v0.10.1

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#1597]
For example, compare [fast_aggregate_verify_62bca7cd61880e26/data.yaml](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/general/phase0/bls/fast_aggregate_verify/small/fast_aggregate_verify_62bca7cd61880e26/data.yaml):

```
input:
  pubkeys: ['0xa491d1b0ecd9bb917989f0e74f0dea0422eac4a873e5e2644f368dffb9a6e20fd6e10c1b77654d067c0618f6e5a7f79a']
  message: '0x0000000000000000000000000000000000000000000000000000000000000000'
  signature: '0xb2a0bd8e837fc2a1b28ee5bcf2cddea05f0f341b375e51de9d9ee6d977c2813a5c5583c19d4e7db8d245eebd4e502163076330c988c91493a61b97504d1af85fdc167277a1664d2a43af239f76f176b215e0ee81dc42f1c011dc02d8b0a31e32'
output: false
```

with [fast_aggregate_verify_009950361f371349/data.yaml](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/general/phase0/bls/fast_aggregate_verify/small/fast_aggregate_verify_009950361f371349/data.yaml):

```
input:
  pubkeys: ['0xa491d1b0ecd9bb917989f0e74f0dea0422eac4a873e5e2644f368dffb9a6e20fd6e10c1b77654d067c0618f6e5a7f79a']
  message: '0x0000000000000000000000000000000000000000000000000000000000000000'
  signature: '0xb2a0bd8e837fc2a1b28ee5bcf2cddea05f0f341b375e51de9d9ee6d977c2813a5c5583c19d4e7db8d245eebd4e502163076330c988c91493a61b97504d1af85fdc167277a1664d2a43af239f76f176b215e0ee81dc42f1c011dc02d8b0a31e32'
output: true
```

Spot the difference? Clue: same input data, different expected result 😂 

PR incoming to fix the generator.
