### ISSUE TITLE
filtered_block_tree fork choice test expected justified checkpoint to change without any new input

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2269]
In v1.1.00-alpha.2, the fork choice test filtered_block_tree contains steps including:

```
<snip>
- {block: block_0x550a5c7bb092ffc787dafa462d75acfb9a9dfbca49451ef9ff3db939c7e26c0b}
- checks:
    time: 144
    head: {slot: 24, root: '0xff0565c092137a448f095479b1d3f73c307a3a59357aa983e9a9f1c1a21a3bca'}
    justified_checkpoint_root: '0x267b47b08d6fa978d84e652e402d0c0784d6dcdff664f49680b83441c287e866'
    finalized_checkpoint_root: '0x267b47b08d6fa978d84e652e402d0c0784d6dcdff664f49680b83441c287e866'
    best_justified_checkpoint: '0x267b47b08d6fa978d84e652e402d0c0784d6dcdff664f49680b83441c287e866'
- checks:
    head: {slot: 24, root: '0xff0565c092137a448f095479b1d3f73c307a3a59357aa983e9a9f1c1a21a3bca'}
    justified_checkpoint_root: '0xad558a267ddc732b65a7f749fc5c28c59304742445ae23642156a116eb2b2d59'
<snip>
```

So it does a bunch of setup, imports that last block then checks a bunch of things including that the `justified_checkpoint_root` is `0x267b47b08d6fa978d84e652e402d0c0784d6dcdff664f49680b83441c287e866`.
Then without any further blocks, attestations or ticks it checks that the `justified_checkpoint_root` has changed to `0xad558a267ddc732b65a7f749fc5c28c59304742445ae23642156a116eb2b2d59`.

Have I missed something or is the test broken?
